root: true
extends:
  - 'zakodium/react'
  - 'zakodium/ts'
  # TODO: enable these rules.
  # - 'zakodium/unicorn'
overrides:
  - files: ['stories/**/*.tsx']
    rules:
      react/no-unstable-nested-components: 0
