name: Playwright tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  playwright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [chromium, firefox, webkit]
        test-type: [ct]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run ${{ matrix.test-type }} tests on ${{ matrix.project }}
        run: npm run playwright-${{ matrix.test-type }} -- --project ${{ matrix.project }}
